name: build-cart-debug

on: 
  push:
    branches: [ master, develop, release,  feature/yariki_w1_ci ]
  pull_request:
    branches: [ master, develop, release, feature/yariki_w1_ci ]

jobs:
  build:
    uses: ./.github/workflows/build-base.yml
    with:
      configuration: Release
      project_file: src/CartingService/CartingService.csproj
      project_test_file: src/CartingService.ComponentTests/CartingService.ComponentTests.csproj